- src/ekam/ekam-client.cpp
It was impossible to pass a log line limit because -l did not consume
its argument, leading to this:
$ ekam-client -l 100
Unknown option: 100
This fixes the behaviour, and additionally checks that the argument in
fact a number.
> Correctly handle -l flag in ekam-client

- src/ekam/rules/compile.ekam-rule
Node changed their ABI for native addons between v0.10 and v4.  For ekam to support nodejs modules intended to be used with node v4, we need to also detect the new symbols.
> Detect nodejs modules built for newer versions of v8

- src/ekam/rules/compile.ekam-rule
Fixes sandstorm-io/sandstorm#2741
> Allow const qualifier on exported nodejs _module symbol.

- src/os/EpollEventManager.cpp
It's worth watching for these events in case MODIFY is not propagated correctly, such as on mounted shared folders inside virtual machine.
In these cases Vagrant plugin like https://github.com/adrienkohlbecker/vagrant-fsnotify will emit sequence ending with CLOSE_WRITE indicating that file might have been modified (as they just use `touch` which opens file for writing but doesn't actually modify it), and plugin like https://github.com/mhallin/vagrant-notify-forwarder will forward just a single ATTRIB event to tell build system to recheck file's mtime.
> Watch for ATTRIB and CLOSE_WRITE inotify events

- README.md
- src/base/Promise.h
- src/ekam/CppActionFactory.cpp
- src/ekam/rules/compile.ekam-rule
- src/ekam/rules/intercept.ekam-rule
- src/ekam/rules/test.ekam-rule
As added to the readme:
> ### Cross-compiling
>
> Ekam currently supports cross-compiling to multiple target architectures at once, by listing additional (non-host) architectures in the `CROSS_TARGETS` environment variable:
>
>     CROSS_TARGETS="aarch64-linux-gnu" ekam
>
> Notes:
> * This is designed to work e.g. with the `crossbuild-essential-*` Debian packages.
> * Ekam always compiles for the host architecture in addition to these targets. This is to support building tools like the Cap'n Proto compiler and then immediately using them in the same build.
> * Ekam assumes the inter-object dependencies are the same on all targets. This tends to mean that it work well for targetting alternate CPU architectures, but not as well for targeting other operating systems.
> * You may specify …
>  Support limited cross-compilation.

- src/ekam/SimpleDashboard.cpp
SimpleDashboard is used when stdout is not a tty. But we still want it to flush proactively so that people can tail the log file or whatever.
> Proactively flush console output in SimpleDashboard.

- Makefile
This should enhance parallelism and cachability for this operation.
Fixes #26 .
> Use separate compile/link steps for bootstrap-ekam

- src/ekam/rules/intercept.c
This syscall has no glibc wrapper, so we can't intercept it with LD_PRELOAD. node12 uses it. Ugh. Let's block it and force node to fall back to regular stat().
> Block the new statx() syscall using seccomp.

- src/ekam/ekam-langserve.c++
- src/ekam/langserve.capnp
- vscode/package.json
- vscode/src/extension.ts
For some reason, if an extension reports diagnostics to vscode, and the user then edits the file, vscode thinks the diagnostics should continue to be located at whatever offset they were first reported at, even if the text under those locations has moved! This makes it really annoying to edit a file that has had errors reported by the ekam plugin.
This PR fixes this problem by subscribing to change notifications and removing all diagnostics when a file is modified. It could be smarter and update the locations of the diagnostics accordingly (which vscode itself really ought to do), but that's more than I care to implement right now.
Depends on: https://github.com/capnproto/capnproto/pull/965
> Fix vscode extension diagnostics becoming out-of-sync with edited file

- vscode/package.json
This resolves a `An accessor cannot be declared in an ambient context.` build error when executing vscode:prepublish. See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#class-field-mitigations
> Update TypeScript dependency to latest version

- vscode/package.json
The `vscode` package is deprecated in favor of `@types/vscode` (and `vscode-test`): https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest
At some point recently the postinstall script we run stopped working also, breaking `npm install` inside this path. I think the extension still has some issues at the moment, but this at least allows `npm install`/`npm run package` to succeed.
> vscode extension: Use `@types/vscode` instead of the vscode postinstall step

- vscode/package.json
It appears that version 7+ of the vscode language client and server have
breaking changes to the API. When pinned to 6.x the extension builds and
works as usual.
---
It looks like 7 came out about a month ago. Here's a snippet from 7+ errors (occur during `npm run package`):
```
node_modules/vscode-languageclient/lib/common/linkedEditingRange.d.ts:6:129 - error TS2694: Namespace '"vscode"' has no exported member 'LinkedEditingRanges'.
6     (this: void, document: code.TextDocument, position: code.Position, token: code.CancellationToken): code.ProviderResult<code.LinkedEditingRanges>;
~~~~~~~~~~~~~~~~~~~
node_modules/vscode-languageclient/lib/common/linkedEditingRange.d.ts:14:201 - error TS2694: Namespace '"vscode"' has no exported member 'LinkedEditingRanges'.
14 …
```
> Pin vscode extension to languageclient/server 6.x

- src/ekam/rules/compile.ekam-rule
When building with LTO you need to use the LLVMGold plugin that matches
the version of Clang that's generating the LTO. Should be "safe" in
terms of not breaking any systems where this isn't available, but may
not enable LTO on all platforms (e.g. if the relative path between clang
and LLVMGold.so isn't "bin/../lib/LLVMGold.so").
> Allow passing in additional arguments to NM (e.g. to specify path to LLVM plugin for LTO files)

- src/ekam/rules/compile.ekam-rule
We `set -u` on all shell scripts, so referencing an undefined variable is an error.
@vlovich
> Fix breakage when NMFLAGS isn't set.

- src/ekam/rules/intercept.c
@kentonv  you merged too quickly :P. This adds some additional color
commentary about why this fix is needed & can never be fixed in
TCMalloc/Abseil.
> Update TCMalloc note in intercept.c

- src/ekam/rules/intercept.c
Revert "Remove unused variable"
This reverts commit 40e0880fe2ffff3e9764a4e7709e3d4997cb4580.
Revert "Update TCMalloc note in intercept.c"
This reverts commit 48764a36a1f00d8fb9db6908a9fae30593249335.
Revert "Don't cause deadlock in TCMalloc"
This reverts commit 4550ccf820301a84efaf19e9cdd358e19d65d477.
cc @vlovich
> Revert SYS_open change that doesn't work on arm.

- src/ekam/rules/intercept.c
The new TCMalloc relies on Abseil & one of the things it does is open
files in /sys/ holding a critical section. Our dlsym to find glibc's
open then causes another invocation of TCMalloc initialization which
causes a deadlock. Neither party is blameless here as both intercepting
`/sys/` is unneeded for Ekam & TCMalloc doing I/O while holding a
critical section is also unfortunate.
TCMalloc issue: https://github.com/google/tcmalloc/issues/78
> Don't cause deadlock in TCMalloc

- src/ekam/rules/compile.ekam-rule
- src/ekam/rules/intercept.c
There's a few things that were needed here.
* EKAM_BYPASS_DIRS - colon-separated list of directories that can be supplied that Ekam treats as passthrough. Needed for the ccache directory.
* Support for treating `/var/run<UID>` as a temporary directory. Could be worked around with ccache environment variables, but since this is a systemd convention, I figured it makes more sense as a part of ekam.
* Add wrapper for stat64. Not sure why this wasn't causing problems before but ccache was tripping up on it.
* Strip off compiler wrappers when linking (otherwise the executable path is nonsense).
> Ccache support

- src/ekam/rules/intercept.c
If Ekam is running some test with the interceptor set, make it possible for sanitizers to properly invoke
the symbolizer without interference from the interceptor. This fixes an issue where building with ASAN/TSAN
causes tests that trigger a sanitizer violation to dump unsymbolicated information to the test log.
Initialization of real_readlink is moved to init_streams_once because we need the non-thunked
version to read /proc/self/exe so early.
> Fix sanitizer symbolizers

- src/ekam/rules/test.ekam-rule
If a test hangs & CI kills it, would be nice to know which test had a
problem (+ have its output dumped).
> Add 30m timeout by default for tests

- src/ekam/rules/intercept.c
This reverts #48.
The interceptor changes caused `capnp` to segfault at startup. Building Ekam itself did not work with these changes.
cc @vlovich
> Revert intercepter

- src/ekam/CppActionFactory.cpp
- src/ekam/CppActionFactory.h
The feature is enabled by EKAM_LIBFUZZER_ENABLE environment variable present.
Whenever an object file exports LLVMFuzzerTestOneInput it will be linked
with -fsanitize=fuzzer argument. The argument can be overriden by
EKAM_LIBFUZZER_LINKER_ARG environment variable.
> libfuzzer support
